### ISSUE TITLE
Healthcheck Path

### ISSUE THREAD

**Issue by scottrobertson** [digitalocean/digitalocean-cloud-controller-manager#117]
Hey

Is there a way to define the healthcheck path for the load balancers?

My problem is that the root is protected by Basic Auth, so it always fails the health check. There is a specific `/health` endpoint i need to call to see if the app is alive or not.

**Comment by andrewsykim** [comment]
@scottrobertson please take a look at https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/117

**Comment by scottrobertson** [comment]
@andrewsykim awesome, thank you. Looks good!

**Comment by scottrobertson** [comment]
Although, i actually switched to using Voyager as i could not work out a way to use 1 load balancer as an ingress for multiple services (using different domains) while using this CCM directly.

**Comment by andrewsykim** [comment]
@scottrobertson yeah, unfortunately, LoadBalancer correlates to Services so there's no simple way to do this (yet). I think a common pattern is to put a LB infront of the ingress so that at least you can do health checking on our ingresses behind a single IP.

**Comment by scottrobertson** [comment]
@andrewsykim i used the following before i switched to DO's kubernetes (i used DO via Stackpoint before), and it worked perfectly. However, for some reason when using DO directly, it does not work.

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: example.com
      http:
        paths:
        - path:
          backend:
            serviceName: example
            servicePort: 80
```

The ingress does not get an address.

It's probably due to it missing something that Stackpoint installed. Maybe haproxy, or nginx or something.
