### ISSUE TITLE
Question on how to access cluster through NodePort

### ISSUE THREAD

**Issue by johndatserakis** [digitalocean/digitalocean-cloud-controller-manager#140]
Hi there - beta DO Kubernetes user here - love the ease of use in setting up the cluster.

One thing that I was having trouble with was accessing the cluster at a NodePort. Sorry for the ignorance.

I've been using k8s on DO for a while now with my own droplets. I use 1 master and 2 nodes. What I'll do is have a service that exposes a specific NodePort, which I can then access by visiting `$DROPLET_IP:$NODEPORT` in the browser. I can do that with the IP's of any of the nodes in the cluster. Works great. I can even spin up a load balancer and point a domain to that exact port.

With the DO k8s beta - the host url I'm given cannot be used the same way. It just gives an error when I try to access it at the port: `$HOSTURL:$NODEPORT`. 

I see that the docs mention to use the host url and not the IP's because the IP's can change. That's fine. But how can I access the NodePort in this case? Below is the example of a service that works great with my own cluster:

```yml
apiVersion: v1
kind: Service
metadata:
  name: $appName
  namespace: $appName
spec:
  type: NodePort
  ports:
  - port: 4000
    nodePort: 30001
  selector:
    app: $appName
    tier: backend
``` 

Also, when trying to access AWS RDS from my cluster, I need to set up firewall access in my RDS dashboard - so what do I put for the IP's of the droplets in my cluster so they are let through? Is the host something I can use here? It is the value I have to put in the `Source` field below. I guess it the main question I have is how to provide the server's IP Address to various services that need it.

<img width="1057" alt="screen shot 2018-10-22 at 10 20 23 am" src="https://user-images.githubusercontent.com/9972969/47297996-aefee400-d5e4-11e8-8de1-a007175b92a2.png">

Thank you
