### ISSUE TITLE
self signed kubelet certificate

### ISSUE THREAD

**Issue by blaugold** [digitalocean/digitalocean-cloud-controller-manager#157]
My use case is scraping metrics from the kubelet through the kubernetes metricbeat module for analysis in elasticsearch and kibana. I have used this [config](https://raw.githubusercontent.com/elastic/beats/6.5/deploy/kubernetes/metricbeat-kubernetes.yaml), provided by elastic, which creates a DaemonSet. Their default config is to let metricbeat use the unsecured http kubelet endpoint without authentication, but it is possible to configure metricbeat to send a bearer token and use https. 

This is my understanding:

do kubletes are configured to authenticate requests. The token in `/var/run/secrets/kubernetes.io/serviceaccount/token` can be used from inside a pod.

do kubletes are using a self signed certificate for serving https:
```bash
[root@amazing-yalow-3ao0 metricbeat]# curl --insecure -v https://localhost:10250 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=amazing-yalow-3ao0@1544591194
* 	start date: Dec 12 04:06:33 2018 GMT
* 	expire date: Dec 12 04:06:33 2019 GMT
* 	common name: amazing-yalow-3ao0@1544591194
* 	issuer: CN=amazing-yalow-3ao0-ca@1544591194
* Connection #0 to host localhost left intact
```

`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` can be used to [verify the cetificate of the api server](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod).

From the directions in the metricbeat config for Red Hat OpenShift, it looks like kubeletes can be configured to serve a certficate which too can be verfied with `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`. 

This is the relevant part of the metricbeat cnofig:

```yaml
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: ${NODE_NAME}
      #hosts: ["localhost:10255"]
      # If using Red Hat OpenShift remove the previous hosts entry and 
      # uncomment these settings:
      hosts: ["https://${HOSTNAME}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl:
        # disable verification since kubelete uses self signed certificate
        verification_mode: none
        certificate_authorities:
          - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```

For now I can collect metrics by disabling verificaiton of the kubelet's certificate. But thats not optimal. This is also relevant to the `metric-server` or other metric collectors. I can get the `metric-server` wokring only with these args:

```yaml
          command:
            - /metrics-server
            - "--kubelet-preferred-address-types=ExternalIP"
            - "--kubelet-insecure-tls"
```

I think #150 might be related.
