### ISSUE TITLE
load balancer health check path not working on 1.11.5 cluster

### ISSUE THREAD

**Issue by marufbd** [digitalocean/digitalocean-cloud-controller-manager#177]
I have the following load balancer conf:
```
apiVersion: v1
kind: Service
metadata:
  annotations:    
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: least_connections
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: my-cert-id
    service.beta.kubernetes.io/do-loadbalancer-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: http
```

Two problems:

From console i see health check is set as:
`http://0.0.0.0:30367/`

and https target droplet port is set to be `32368` instead of `30367`
