### ISSUE TITLE
Handle situation where HTTP-to-HTTPS redirection is enabled but HTTPS service port is missing

### ISSUE THREAD

**Issue by timoreimann** [digitalocean/digitalocean-cloud-controller-manager#192]
Given a service spec like

```yaml
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
```

HTTP-to-HTTPS won't work because the spec is missing an HTTPS service port like: 

```yaml
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
```

We should try to detect the problem and surface an error message / event.
