### ISSUE TITLE
Should healthcheck path default to /healthz when healthcheck-protocol is "http"?

### ISSUE THREAD

**Issue by erkie** [digitalocean/digitalocean-cloud-controller-manager#195]
The nginx ingress controller has a concept of "default backend". This is the backend that is used when no `Host` header is specified on incoming requests. The default backend is defined as a backend that: 1. returns `404` on `GET /` and 2. `200` on `GET /healthz`. https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/ I assume it's so loadbalancers in front of the ingress controller can take the server out of rotation if there are no available services?

When the protocol is set to HTTP in the k8s loadbalancer service as follows:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "false"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "<certificate id>"
```

In the DO Loadbalancer, the healthcheck is setup as an HTTP request to the HTTP port on the node.

<img width="513" alt="Screenshot 2019-03-14 22 42 41" src="https://user-images.githubusercontent.com/21059/54393575-ce3d0180-46aa-11e9-955d-714d9518ca03.png">

This put all my nodes in a perpetual Down state:

<img width="168" alt="Screenshot 2019-03-14 22 47 26" src="https://user-images.githubusercontent.com/21059/54393746-3ab80080-46ab-11e9-8dbf-fffd046ad402.png">

A simple curl from within the server confirms that the port that the DO loadbalancer is trying to access returns `404`

```
$ curl localhost:32179/
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
```

But `/healthz` gives a 200.

```
curl localhost:32179/healthz -vvv
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 32179 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:32179
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.15.9
```

Changing the healthcheck path to `/healthz` fixes everything:

```yaml
service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz"
```

Obviously if you don't use the nginx ingress controller you will probably not run into this problem. And `/healthz` path seems to be a fairly standard kubernetism, but definitely not industry standard and widespread enough to be on by default.

It was definitely not easy finding all this, so I wonder if just some documentation somewhere might help? I'm curious how other providers handles this. Should the default healthcheck for K8s loadbalancers just be TCP? What are your thoughts?
