### ISSUE TITLE
tls-ports annotation is ignored when using http2 

### ISSUE THREAD

**Issue by andykent** [digitalocean/digitalocean-cloud-controller-manager#254]
Just updated my cluster hopping to switch to http2 but when changing from `http` to `http2` it also switched port 80 to http2 which I don't think is the expected behaviour. 

The docs state...

> service.beta.kubernetes.io/do-loadbalancer-tls-ports
> Specify which ports of the loadbalancer should use the https or http2 protocol.

But the following config produces a LB with http2 as the protocol for both ports 80 and 443...

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: least_connections
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: xxx
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: /_health
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-protocol: http2
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
  labels:
    app: days
spec:
  ports:
  - name: http
    port: 80
    targetPort: 4000
  - name: https
    port: 443
    targetPort: 4000
```

Switching the protocol to `http` has the expected behaviour of port 80 - http, port 443 - https.
