### ISSUE TITLE
Getting a HTTPS load balancer from HTTP2 configuration

### ISSUE THREAD

**Issue by sjparkinson** [digitalocean/digitalocean-cloud-controller-manager#299]
I'm using the following configuration to try and specify a HTTP2 load balancer, but I'm ending up with a HTTPS configuration for some reason. Any ideas on what I've missed?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http2"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "0eb327fc-4b97-49d8-ab90-d9f4c6a96b44"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http2
      protocol: TCP
      port: 443
      targetPort: 80
```

The configuration in my dashboard...

![image](https://user-images.githubusercontent.com/51677/69884346-e358cf80-12cf-11ea-9a98-ee58e63f64bd.png)

And from `kubectl describe`...

![image](https://user-images.githubusercontent.com/51677/69884362-fb305380-12cf-11ea-9501-adf7aead18ce.png)
