### ISSUE TITLE
Getting "Kubernetes Ingress Controller Fake Certificate"

### ISSUE THREAD

**Issue by IljaDaderko** [digitalocean/digitalocean-cloud-controller-manager#321]
I was following examples for https with custom certificate to set up https://hasura.io server and ended up with config file below. It seems to set everything up correctly, but every time I visit my domain I get `NET::ERR_CERT_AUTHORITY_INVALID` error  in chrome, upon inspecting the certificate it seems to be using some default value of

> Kubernetes Ingress Controller Fake Certificate

I'm not sure if I am missing something, but believe this could be a bug? I ensured to check that I specify correct id for certificate and that my dns records are correct. Using `kubectl describe` on my load balancer service also seems to output all the correct data.

My config file looks like this:
```yaml
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: hasura-server-load-balancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "1-2-3-4-5"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "my.api-domain.dev"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: hasura-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
---
# Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-server
  template:
    metadata:
      labels:
        app: hasura-server
    spec:
      containers:
        - image: hasura/graphql-engine:v1.2.1
          imagePullPolicy: IfNotPresent
          name: hasura-server
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgresql://...
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: password
          ports:
            - containerPort: 8080
              protocol: TCP
```
