### ISSUE TITLE
service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443" is ignored!

### ISSUE THREAD

**Issue by aholbreich** [digitalocean/digitalocean-cloud-controller-manager#324]
My config
```
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
```
however Loadbalancer ignored 443 port settiong and is still listening on 80. Same shown on Digital Ocean Admin Console

**Comment by timoreimann** [comment]
Does this show all of the LB-specific annotations you have set? My guess is you missed to specify the certificate ID or TLS pass-through, one of which must be given when HTTPS is used.

See also https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/annotations.md#servicebetakubernetesiodo-loadbalancer-tls-ports, especially the second paragraph.

**Comment by aholbreich** [comment]
Hi @timoreimann  unfortunatley your guess is wrong.
cer't id was given all the time. here my current setup:

```
service.beta.kubernetes.io/do-loadbalancer-certificate-id: "cb7187e9-xxxxx"
service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
service.beta.kubernetes.io/do-loadbalancer-hostname: "a.b.c.com"
service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
```
all annotations work except port 443. i have to go to the UI and uopdate it from 80 to 443 :( after evy change

**Comment by aholbreich** [comment]
@timoreimann is there way to gather debug information or watch the logs?

**Comment by aholbreich** [comment]
Clarifying "ignored". It's even always set to "80" even if it was correcten in the UI manually as soon Kubernetes Service resource is touched.

**Comment by mman** [comment]
I have it setup as http with forced redirect and it seems to work, I created the LB several months ago and updated it to add the ``do-loadbalancer-name`` annotation after the last DO release.

```
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "xyz"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "a.b.c.d"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "false"
    service.beta.kubernetes.io/do-loadbalancer-name: "xyz"
```

**Comment by timoreimann** [comment]
@aholbreich it almost sounds like you have a Service Port definition provided for port 80 but none for port 443. Could you please share your full Service manifest?

**Comment by timoreimann** [comment]
Also worth noting that errors are propagated as events in the namespace of the Service. Not sure if it'd help you here since it doesn't seem to be about a legitimate error.

And yeah, changes done to the LB in the DO control panel are reconciled away by design. All configuration should go through the Service object.

**Comment by aholbreich** [comment]
```
---
kind: Service
apiVersion: v1
metadata:
  name: abc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "cb7187e9-fb7f-4b91-b690-abc"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "abc.me"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-name: "lb1"
spec:
  type: LoadBalancer
  selector:
    app: lyricsforme
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
```
this is the last one:

P.S. this docu 
https://www.digitalocean.com/docs/kubernetes/how-to/configure-load-balancers/#ssl-certificates
gives example with:
`service.beta.kubernetes.io/do-loadbalancer-protocol: "http"`
shouldn't it be 'https'?
