### ISSUE TITLE
secret of type `data` created by Terraform doesn't work

### ISSUE THREAD

**Issue by jimangel** [digitalocean/digitalocean-cloud-controller-manager#327]
Is the secret data `stringData` a requirement for the token secret?

I was testing adding the CCM secret via Terraform with:
```
# from terraform
resource "kubernetes_secret" "digitalocean_ccm_token" {
  metadata {
    name = "digitalocean"
    namespace = "kube-system"
  }
  data = {
    access-token = var.do_token
  }
}
```

I can validate that the secret exists, it is base64 encoded. I can decode it to match the working example of:

```
# from localhost
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  access-token: $DO_PAT
EOF
```

When created with `data` in Terraform I see:
```
Error syncing load balancer: failed to ensure load balancer: failed to build load-balancer request: failed to list all droplets: GET https://api.digitalocean.com/v2/droplets?page=1&per_page=200: 401 Unable to authenticate you
```

Cluster details:
* [kubernetes](https://github.com/kubernetes/kubernetes) v1.18.3
* [docker](https://github.com/docker/docker-ce) v19.03.11
* [coredns](https://github.com/coredns/coredns) v1.6.7
* [cilium cni](https://github.com/cilium/cilium) v1.7.2
* [ubuntu](https://ubuntu.com/) 20.04 LTS
