### ISSUE TITLE
I can't do this http2 + with cert + redirect http to https !

### ISSUE THREAD

**Issue by phamquyhai** [digitalocean/digitalocean-cloud-controller-manager#334]
Hi everyone !
Current i using https with cert + redirect. It's OK.
```
....
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: 67514dca-185a-4279-bd8c-b1eeca6f9633
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
name: kong-proxy
  namespace: kong
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8000
....
```

But i added support http2 not working:

```
....
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http2"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: 67514dca-185a-4279-bd8c-b1eeca6f9633
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
name: kong-proxy
  namespace: kong
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8000
....
```

Please help me 😊😊😊😊😊😊😊
