### ISSUE TITLE
SSL termination not working end-to-end with Kong

### ISSUE THREAD

**Issue by kubevious** [digitalocean/digitalocean-cloud-controller-manager#351]
We are running Kong 2.1. Trying to terminate the SSL on the LB (certificate & domain managed by DO), and then forward to the Kong Proxy with HTTPS. 

Here is the configuration on the LoadBalancer Service:
```yaml
annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "my-best-lb-ever-if-we-make-it-work-eventually"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "*****************"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
```

This creates a forwarding rule like this. 
![img](https://i.imgur.com/LQmMIxr.jpg)

But that port 31709 corresponds to a HTTPS Kong proxy endpoint. Obviously, Kong complains about and HTTP packet sent to HTTPS server. 

Changing it manually to HTTPS does the trick, but this is definitely not an approach that can work in production. This would eventually get reverted back to HTTP and the entire service would be unaccessible.
![img](https://i.imgur.com/LIBqREf.jpg)

**Comment by timoreimann** [comment]
👋

I'm getting 403s on the image links you embedded, but I think I get your request. What you're asking for is indeed not possible right now due to configuration limitations on CCM, but should be fairly easy to support through yet another configuration option. I'm happy to keep the ticket open to track the effort.

One note: the LB sends traffic into the droplets over the internal interface / VPC. I can see how HTTPS could still be desirable for extra security reasons or because applications might be easier to use on HTTPS. I wanted to mention it though to rule out potential misunderstandings on what goes over the public vs. the private network.

Thanks!

**Comment by timoreimann** [comment]
Another quick point / question: is TLS pass through an option for you? If not, could you share why TLS termination is needed in your case?

**Comment by rubenhak** [comment]
@timoreimann, updated the image urls for your reference. Please recheck the original post.

We can sacrifice HTTPS between the LB/Kong proxy, but we have to terminate the TLS on the LB in order to make use of cloud managed certificates and also to have x-forwarded-for header populated. Headers values cannot be modified unless the TLS is terminated at the LB.

So we are using Kong as api gateway. If you guys cannot allow HTTPS configuration after TLS termination as of right now, could you please help with Kong configuration to make the communication work?

Here are the overrides for Kong helm chart:
```yaml
ingressController:
  enabled: true
  installCRDs: false

admin:
  enabled: true
  http:
    enabled: false

proxy:
  enabled: true
  http:
    enabled: false
  tls:
    enabled: true
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "*******************"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "*********************"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
```

FYI, if `proxy.http.enabled=true` and `proxy.tls.enabled=false` is set, the LB gets configured without HTTPS.
