### ISSUE TITLE
LoadBalancer Reconciliation does not correctly resolve forwarding rules

### ISSUE THREAD

**Issue by jrkarnes** [digitalocean/digitalocean-cloud-controller-manager#360]
### What is going wrong?

As far as we can tell, the LoadBalancer reconciliation loop is actually not respecting service definitions, or is incorrectly resolving them.

### How do we know this is happening?

We have now twice had our load balancer just randomly clear its forwarding settings.

The first time this issue happened, we believed that it was a fluke; however, it has now happened a second time and we're officially designating this as a *problem*.

### How do we know its an issue?

According to this piece of the readme, manual adjustments of the LoadBalancer are not supposed to take place. According to the documentation, the only safe way of making these adjustments permanent is to alter the `Service` object in Kubernetes. We have done this in a somewhat round-about way; however, the method we've chosen is somewhat of a standard application of our Ingress service (Traefik).

### May we see some code please?

Sure.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "ab160026-2446-44ef-bcc7-021a2b00f1fb"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-name: "production-load-balancer"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
```

As you can see from the above manifest set, there isn't _anything_ there which should be rejected by a reconciler... yet, every time the reconciler runs, our LB settings are completely wiped out.

By our understanding, this _shouldn't_ be happening.

We look forward to a response.
