### ISSUE TITLE
ingress-nginx: 400 Bad Request The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by shinebayar-g** [digitalocean/digitalocean-cloud-controller-manager#368]
I'm getting `400 Bad Request The plain HTTP request was sent to HTTPS port` error with Kubernetes ingress-nginx.

my nginx config:

```yml
controller:
  config:
    use-proxy-protocol: "true"

  service:
    enabled: true

    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: "my-ingress-controller"
      service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
      service.beta.kubernetes.io/do-loadbalancer-certificate-id: "aa536df2-6e76-4811-b56f-07e82a2cf123"
      service.beta.kubernetes.io/do-loadbalancer-http-ports: "80"
      service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
      service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
      service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
      service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
```

My Ingress config:

```yml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: test-nginx
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-nginx
                port:
                  number: 80
```

What am I missing?
