### ISSUE TITLE
Extending Loadbalancer timeout duration

### ISSUE THREAD

**Issue by echan00** [digitalocean/digitalocean-cloud-controller-manager#396]
Some of my kubernetes cluster requests are returning 502s. I believe this is due to a timeout issue with my loadbalancer because some requests are taking a while to process. Is it possible to extend this timeout duration?

```
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    run: flask-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "74143023-e4b1-4857-bff0-37e1dea945ad"
spec:
  selector:
    app: flask
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 5000
  - name: https
    protocol: "TCP"
    port: 443
    targetPort: 5000    
  type: LoadBalancer
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask  
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        imagePullPolicy: Always
        image: gcr.io/xxx/flask:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.9
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
```
