### ISSUE TITLE
Misconfigured cloud-controller-manager.yml (HA deployment that uses daemonset)

### ISSUE THREAD

**Issue by jekakm** [digitalocean/digitalocean-cloud-controller-manager#397]
After deploying got errors:
```
E1119 10:01:56.059612       1 leaderelection.go:325] error retrieving resource lock kube-system/cloud-controller-manager: leases.coordination.k8s.io "cloud-controller-manager" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

So need to add more permissions to make it works:
```
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - watch
  - update
```
